### ISSUE TITLE
Gridcoin 5.1.0.0 build seems to be having issues with Big Sur

### ISSUE THREAD

**Issue by jamescowens** [Git-Jiro/homebrew-jiro#86] opened 2020-11-30 05:27 UTC
We have been getting reports that the 5.1 build will not run on Big Sur. This appears to be a regression from 5.0.2.0 based on reports in the field. Can you please look into it ASAP?  The hard fork is in less than one day.

**Comment by scribblemaniac** [comment] 2020-11-30 14:29
Anyone can use the homebrew formula in this repository rather than the binary/cask. Based on a couple reports it works fine when installed on Big Sur. Yes the binary should be fixed, but for a quick fix this is the way to go.

**Comment by jamescowens** [comment] 2020-11-30 16:12
Yes @scribblemaniac, although most MacOS users do not, and will not go through that hassle. The binary build needs to be fixed.

**Comment by joemosch** [comment] 2020-12-01 18:27
> Yes @scribblemaniac, although most MacOS users do not, and will not go through that hassle. The binary build needs to be fixed.

I tried going the Homebrew route, but I don't know what I'm doing. It won't install the ComandLineTools.
The DMG binary needs to be updated, you can't rely on casual people installing from the Terminal.

**Comment by Git-Jiro** [comment] 2020-12-02 17:10
The DMG file is generated with an old version of X-Code because people wanted the dmg to work with older mac OS versions. Building it directly in Big Sur seems to work.

Therefore I would conclude if i update to a more recent version of X-Code it will not work on such old mac OS versions anymore, but it will work on Big Sur.

**Comment by RoboticMind** [comment] 2020-12-02 17:44
Why not just put two dmg files on each release thing? One file for the newer versions and one for the older versions

**Comment by jamescowens** [comment] 2020-12-02 18:42
That is what I was suggesting..

**Comment by Git-Jiro** [comment] 2020-12-02 18:57
That will only work as long as Travis CI still allows to build on (older) mac OS builds for free.

**Comment by Git-Jiro** [comment] 2020-12-02 19:04
Github Actions does not support older mac OS versions.

**Comment by digitalmediaguy** [comment] 2020-12-02 21:52
I am one of these users (trying to get it working on Big Sur) and have tried using homebrew but get errors on installation. I am new to homebrew so could be me but I tried both methods.

Most recently...

**brew tap Git-Jiro/jiro
brew install gridcoin**

and before that I tried...

**brew tap git-jiro/jiro-casks
brew cask install gridcoin**

The non-cask method (first one above) resulted in the following errors...

Gridcoin 5.1.0.0 build seems to be having issues with Big Sur https://github.com/Git-Jiro/homebrew-jiro/issues/86
Gridcoin does not run in MacOS Catalina 10.15.5 https://github.com/Git-Jiro/homebrew-jiro/issues/78

Not sure if this is helpful but figured I would pass it along.

**Comment by Git-Jiro** [comment] 2020-12-03 18:35
Hello!
I have a new build to test: https://github.com/Git-Jiro/homebrew-jiro/releases/download/vaction_test3/gridcoinresearch_bigsur.dmg

It was actually build using a catalina image, but anyway please test if it works on bigsur.

**Comment by RoboticMind** [comment] 2020-12-03 23:30
> Github Actions does not support older mac OS versions.

Looks like they might support back to MacOS 10.13 which I believe is the version you were using previously with travis? https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.13-Readme.md

**Comment by Git-Jiro** [comment] 2020-12-04 16:33
ok, good to know. Then I will try to setup a build that uses multiple macOS versions.

**Comment by evitiello** [comment] 2020-12-04 16:56
@git-jiro The Big Sur build you posted is working for me - thank you!

**Comment by digitalmediaguy** [comment] 2020-12-05 01:05
@Git-Jiro also appears to be working for me now! Much appreciated. Thank you.

**Comment by evitiello** [comment] 2020-12-14 00:10
I'm not sure if this is expected behavior or not, or whether it is a bug in this build, I've never seen it before, but since installing this version I constantly have over a dozen incoming transactions, all for ~10GRC that never seem to get completely verified, they timeout and then reappear.

**Comment by scribblemaniac** [comment] 2020-12-14 00:31
@evitiello You are forked, likely because you ran an older version after the hardfork point. Going to the menu and doing a Snapshot Download should fix the issue. If not you may have to delete the blockchain files manually and resync from 0.

**Comment by evitiello** [comment] 2020-12-14 22:11
Ah I see. thank you!

**Comment by Git-Jiro** [comment] 2021-09-12 16:45
closed since 5.1.0.0 is an old version of Gridcoin and should not be used anymore

**Closed as completed by Git-Jiro** 2021-09-12 16:45 UTC
